name: CI-debug

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  ci-debugging:
    name: CI debugging
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6']

    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
        with:
           auto-update-conda: true
           auto-activate-base: false
           environment-file: envs/environment-test.yaml
           python-version: ${{ matrix.python-version }}
           activate-environment: debug-test

      - name: Install package
        shell: bash -l {0}
        run: |
          python3 -m pip install -vvv --src $GITHUB_WORKSPACE/../vcs_pkgs/ --editable hg+https://bitbucket.org/salishsea/tools#egg=SalishSeaTools&subdirectory=SalishSeaTools
